### PR TITLE
Fixed Compilation Error

### PR DESCRIPTION
**Pull request by IcyHot09**
Included "Dot.cpp" instead of "Dot.h" in main.cpp to fix error during compilation

### CODE REVIEW

**Comment by Emilieczq** [comment]
Sorry, it works well on my laptop with "Dot.h" included in main.cpp, but has errors with "Dot.cpp". You can check this on https://www.geeksforgeeks.org/write-header-file-c/ :)

**Comment by IcyHot09** [comment]
But shouldn't it work on all systems alike? Including Dot.h File and Compiling on Linux gave errors.

**Comment by Emilieczq** [comment]
Yes, I tried it on Windows and on MacOS. You can try with "make clean" then "make" commands or just delete all other files except the main.cpp, Dot.h, Dot.cpp, makefile and Readme.md. If it still doesn't work, you can copy your errors here.

**Comment by Emilieczq** [comment]
By the way, there is a small error with the random color (not correct color after clicking random then clicking another color), I'll fix it now.

**Comment by IcyHot09** [comment]
Well I'm Adding Some features to it. Like Animation when drawing a line and other shapes. Also increasing and decreasing no of lines of symmetry in your pattern generator.

**Pull request closed without merging**
